Repository PLANlT/planit-client, pull requests merged in 2025-07, with the labels that each got.

#34 [Feat] 메인 태스크 달성 인터랙션
  .gitignore
  assets/icons/check.svg
  assets/images/congratulation.svg
  assets/images/guilty_free_reason1.svg
  assets/images/guilty_free_reason2.svg
  assets/images/guilty_free_reason3.svg
  assets/images/guilty_free_reason4.svg
  assets/images/recovery_routine_phone.svg
  assets/mascots/first_complete1.svg
  assets/mascots/first_complete2.svg
  assets/mascots/relaxing.svg
  assets/mascots/restarting.svg
  assets/mascots/sleeping.svg
  assets/mascots/thinking.svg
  fonts/BlackHanSans-Regular.ttf
  fonts/Pretendard-Black.ttf
  lib/main.dart
  lib/theme/planit_colors.dart
  lib/theme/planit_typos.dart
  lib/ui/common/assets.dart
  lib/ui/common/comopnent/planit_toast.dart
  lib/ui/main/component/plan_list_view.dart
  lib/ui/main/component/route_switch_banner.dart
  lib/ui/main/component/task_widget.dart
  lib/ui/main/main_state.dart
  lib/ui/main/main_state.freezed.dart
  lib/ui/main/main_view.dart
  lib/ui/main/main_view_model.dart
  lib/ui/main/view/first_complete_view.dart
  pubspec.yaml
Labels: ✨ Feature

#37 Pl 142/refactor/chang/plan create mvvm
  lib/repository/plan/model/plan_model.dart
  lib/repository/plan/model/plan_overview_model.dart
  lib/repository/plan/plan_repository.dart
  lib/ui/plan/component/plan_list_card.dart
  lib/ui/plan/component/plan_wrap_grid.dart
  lib/ui/plan/plan_create/plan_create_state.dart
  lib/ui/plan/plan_create/plan_create_state.freezed.dart
  lib/ui/plan/plan_create/plan_create_view.dart
  lib/ui/plan/plan_create/plan_create_view_model.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_edit/plan_edit_bottom_sheet_state.dart
  lib/ui/plan/plan_detail/plan_detail_state.dart
  lib/ui/plan/plan_main/plan_state.dart
  lib/ui/plan/plan_main/plan_state.freezed.dart
  lib/ui/plan/plan_main/plan_view.dart
  lib/ui/plan/plan_main/plan_view_model.dart
Labels: 🔨 Refactor

#39 [Feat] 회복 루틴
  lib/service/storage/storage_key.dart
  lib/theme/planit_typos.dart
  lib/ui/common/view/default_layout.dart
  lib/ui/main/component/recovery_routine_banner.dart
  lib/ui/main/main_view.dart
  lib/ui/main/main_view_model.dart
  lib/ui/recovery/component/recovery_bg.dart
  lib/ui/recovery/component/recovery_timer.dart
  lib/ui/recovery/recovery_complete_view.dart
  lib/ui/recovery/recovery_deep_breath_view.dart
  lib/ui/recovery/recovery_description_view.dart
  lib/ui/recovery/recovery_intro_view.dart
  lib/ui/recovery/recovery_small_action_view.dart
  lib/ui/recovery/recovery_stop_phone_view.dart
Labels: ✨ Feature

#38 [Feat] 길티 프리
  assets/images/speach_balloon.svg
  lib/core/guilty_free_status.dart
  lib/main.dart
  lib/repository/guilty_free/guilty_free_repository.dart
  lib/service/app/app_service.dart
  lib/service/app/app_state.dart
  lib/service/app/app_state.freezed.dart
  lib/service/storage/storage_key.dart
  lib/ui/common/assets.dart
  lib/ui/common/view/root_tab.dart
  lib/ui/guilty_free/const/guilty_free_reasons.dart
  lib/ui/guilty_free/ing/guilty_free_history_view.dart
  lib/ui/guilty_free/ing/guilty_free_ing_state.dart
  lib/ui/guilty_free/ing/guilty_free_ing_state.freezed.dart
  lib/ui/guilty_free/ing/guilty_free_ing_view.dart
  lib/ui/guilty_free/ing/guilty_free_ing_view_model.dart
  lib/ui/guilty_free/start/guilty_free_start_state.dart
  lib/ui/guilty_free/start/guilty_free_start_state.freezed.dart
  lib/ui/guilty_free/start/guilty_free_start_view_model.dart
  lib/ui/guilty_free/start/view/guilty_free_blocked_view.dart
  lib/ui/guilty_free/start/view/guilty_free_intro_view.dart
  lib/ui/guilty_free/start/view/guilty_free_reason_view.dart
  lib/ui/main/component/main_top_widget.dart
  lib/ui/main/main_state.dart
  lib/ui/main/main_state.freezed.dart
  lib/ui/main/main_view.dart
  lib/ui/main/main_view_model.dart
  lib/ui/splash_view.dart
  lib/utils/date_time.dart
Labels: ✨ Feature

#57 [Feat] 메인 (거의) 완성
  lib/core/api_response.dart
  lib/core/api_response.g.dart
  lib/core/error_message.dart
  lib/data_source/main/main_data_source.dart
  lib/data_source/main/main_data_source.g.dart
  lib/data_source/main/reponse_body/today_tasks_response_body.dart
  lib/data_source/main/reponse_body/today_tasks_response_body.g.dart
  lib/repository/main/main_repository.dart
  lib/repository/main/model/main_plan_model.dart
  lib/service/storage/storage_key.dart
  lib/ui/common/comopnent/planit_bottom_sheet.dart
  lib/ui/main/component/main_top_widget.dart
  lib/ui/main/component/plan_list_view.dart
  lib/ui/main/component/recovery_routine_banner.dart
  lib/ui/main/component/task_widget.dart
  lib/ui/main/const/main_enums.dart
  lib/ui/main/main_state.dart
  lib/ui/main/main_state.freezed.dart
  lib/ui/main/main_view.dart
  lib/ui/main/main_view_model.dart
  lib/ui/recovery/recovery_complete_view.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature

#59 [Feat] 길티프리 API 연동
  lib/data_source/guilty_free/guilty_free_data_source.dart
  lib/data_source/guilty_free/guilty_free_data_source.g.dart
  lib/data_source/guilty_free/response_body/guilty_free_date_response_body.dart
  lib/data_source/guilty_free/response_body/guilty_free_date_response_body.g.dart
  lib/data_source/guilty_free/response_body/guilty_free_reason_list_response_body.dart
  lib/data_source/guilty_free/response_body/guilty_free_reason_list_response_body.g.dart
  lib/repository/guilty_free/guilty_free_repository.dart
  lib/repository/guilty_free/model/guilty_free_date_model.dart
  lib/repository/guilty_free/model/guilty_free_reason_list_model.dart
  lib/ui/common/comopnent/planit_button.dart
  lib/ui/guilty_free/const/guilty_free_reasons.dart
  lib/ui/guilty_free/ing/guilty_free_history_view.dart
  lib/ui/guilty_free/ing/guilty_free_ing_view.dart
  lib/ui/guilty_free/ing/guilty_free_ing_view_model.dart
  lib/ui/guilty_free/ing/history/guilty_free_history_state.dart
  lib/ui/guilty_free/ing/history/guilty_free_history_state.freezed.dart
  lib/ui/guilty_free/ing/history/guilty_free_history_view.dart
  lib/ui/guilty_free/ing/history/guilty_free_history_view_model.dart
  lib/ui/guilty_free/start/guilty_free_start_state.dart
  lib/ui/guilty_free/start/guilty_free_start_state.freezed.dart
  lib/ui/guilty_free/start/guilty_free_start_view_model.dart
  lib/ui/guilty_free/start/view/guilty_free_intro_view.dart
  lib/ui/guilty_free/start/view/guilty_free_reason_view.dart
Labels: ✨ Feature

#60 [Feat] 온보딩
  assets/mascots/splash.svg
  assets/onboarding/onboarding1.svg
  assets/onboarding/onboarding2-1.svg
  assets/onboarding/onboarding2-2.svg
  assets/onboarding/onboarding2-3.svg
  assets/onboarding/onboarding3.svg
  assets/onboarding/onboarding4.svg
  lib/main.dart
  lib/ui/common/assets.dart
  lib/ui/onboarding/onboarding_first_tap.dart
  lib/ui/onboarding/onboarding_fourth_tap.dart
  lib/ui/onboarding/onboarding_layout.dart
  lib/ui/onboarding/onboarding_second_tap.dart
  lib/ui/onboarding/onboarding_third_tap.dart
  lib/ui/onboarding/onboarding_view.dart
  lib/ui/splash_view.dart
  pubspec.yaml
Labels: ✨ Feature

#67 [PL-185] fix: 네이버 로그인 accessToken 수정
  lib/repository/auth/auth_repository.dart
Labels: 🐞 BugFix

#71 Pl 122/feat/chang/plan api connect
  assets/templates/money.svg
  lib/data_source/plan/plan_data_source.dart
  lib/data_source/plan/plan_data_source.g.dart
  lib/data_source/plan/reponse_body/plan_create_response_body.dart
  lib/data_source/plan/reponse_body/plan_create_response_body.g.dart
  lib/data_source/plan/reponse_body/plan_response_body.dart
  lib/data_source/plan/reponse_body/plan_response_body.g.dart
  lib/data_source/plan/request_ body/plan_request_body.dart
  lib/data_source/plan/request_ body/plan_request_body.g.dart
  lib/data_source/task/response_body/routine_response_body.dart
  lib/data_source/task/response_body/routine_response_body.g.dart
  lib/data_source/task/task_data_source.dart
  lib/data_source/task/task_data_source.g.dart
  lib/repository/plan/model/plan_create_model.dart
  lib/repository/plan/model/plan_model.dart
  lib/repository/plan/plan_repository.dart
  lib/repository/task/model/routine_model.dart
  lib/repository/task/task_repository.dart
  lib/ui/plan/component/plan_list_card.dart
  lib/ui/plan/component/template_detail_card.dart
  lib/ui/plan/component/template_list.dart
  lib/ui/plan/plan_create/plan_create_view.dart
  lib/ui/plan/plan_create/plan_create_view_model.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_more/plan_more_bottom_sheet_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_edit/task_edit_bottom_sheet_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_edit/task_edit_bottom_sheet_view_model.dart
  lib/ui/plan/plan_detail/plan_detail_view.dart
  lib/ui/plan/plan_main/plan_view.dart
  lib/ui/plan/plan_main/plan_view_model.dart
  lib/ui/plan/plan_template/plan_teamplate_view.dart
  lib/ui/plan/plan_template/plan_template.dart
  lib/ui/plan/plan_template/plan_template_detail_view.dart
  lib/ui/plan/plan_template/plan_template_detail_view_model.dart
  lib/ui/plan/plan_template/plan_template_state.dart
  lib/ui/plan/plan_template/plan_template_state.freezed.dart
Labels: ✨ Feature

#73 [Feat] 메인 관련 화면 Go-router 연동
  assets/icons/nav_archive.svg
  assets/icons/nav_home.svg
  assets/icons/nav_plan.svg
  lib/data_source/main/reponse_body/today_tasks_response_body.dart
  lib/data_source/main/reponse_body/today_tasks_response_body.g.dart
  lib/repository/main/model/main_plan_model.dart
  lib/routes/app_router.dart
  lib/ui/common/assets.dart
  lib/ui/common/view/default_layout.dart
  lib/ui/common/view/root_tab.dart
  lib/ui/guilty_free/ing/guilty_free_ing_view.dart
  lib/ui/guilty_free/ing/history/guilty_free_history_view.dart
  lib/ui/guilty_free/start/guilty_free_start_view_model.dart
  lib/ui/guilty_free/start/view/guilty_free_blocked_view.dart
  lib/ui/guilty_free/start/view/guilty_free_intro_view.dart
  lib/ui/guilty_free/start/view/guilty_free_reason_view.dart
  lib/ui/main/component/main_top_widget.dart
  lib/ui/main/component/recovery_routine_banner.dart
  lib/ui/main/component/task_widget.dart
  lib/ui/recovery/recovery_complete_view.dart
  lib/ui/recovery/recovery_deep_breath_view.dart
  lib/ui/recovery/recovery_description_view.dart
  lib/ui/recovery/recovery_intro_view.dart
  lib/ui/recovery/recovery_small_action_view.dart
  lib/ui/recovery/recovery_stop_phone_view.dart
  lib/ui/splash_view.dart
  pubspec.lock
Labels: ✨ Feature

#81 Pl 164/feat/chang/archive api
  lib/data_source/archiving/archiving_data_source.dart
  lib/data_source/archiving/archiving_data_source.g.dart
  lib/data_source/archiving/response_body/archiving_plan_response_body.dart
  lib/data_source/archiving/response_body/archiving_plan_response_body.g.dart
  lib/data_source/archiving/response_body/archiving_restart_plan_response_body.dart
  lib/data_source/archiving/response_body/archiving_restart_plan_response_body.g.dart
  lib/data_source/plan/plan_data_source.dart
  lib/data_source/plan/plan_data_source.g.dart
  lib/data_source/plan/reponse_body/archiving_complete_plan_response_body.dart
  lib/data_source/plan/reponse_body/archiving_complete_plan_response_body.g.dart
  lib/repository/archiving/archiving_repository.dart
  lib/repository/archiving/model/archiving_complete_model.dart
  lib/repository/archiving/model/archiving_plan_model.dart
  lib/repository/archiving/model/archiving_restart_model.dart
  lib/repository/plan/plan_repository.dart
  lib/theme/planit_typos.dart
  lib/ui/archiving/archiving_complete/archiving_complete_naviagtor.dart
  lib/ui/archiving/archiving_complete/archiving_complete_view.dart
  lib/ui/archiving/archiving_detail/archiving_detail_view.dart
  lib/ui/archiving/archiving_main/archiving_state.dart
  lib/ui/archiving/archiving_main/archiving_state.freezed.dart
  lib/ui/archiving/archiving_main/archiving_view.dart
  lib/ui/archiving/archiving_main/archiving_view_model.dart
  lib/ui/archiving/archiving_restart/archiving_restart_state.dart
  lib/ui/archiving/archiving_restart/archiving_restart_state.freezed.dart
  lib/ui/archiving/archiving_restart/archiving_restart_view.dart
  lib/ui/archiving/archiving_restart/archiving_restart_view_model.dart
  lib/ui/common/view/root_tab.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_more/plan_more_bottom_sheet_state.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_more/plan_more_bottom_sheet_state.freezed.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_more/plan_more_bottom_sheet_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_more/plan_more_bottom_sheet_view_model.dart
  lib/ui/plan/plan_detail/plan_detail_view.dart
  lib/ui/plan/plan_detail/plan_detail_view_model.dart
Labels: ✨ Feature

#80 Pl 117/feat/chang/plan gorouter setting
  lib/routes/app_router.dart
  lib/ui/plan/component/plan_list_card.dart
  lib/ui/plan/component/template_detail_card.dart
  lib/ui/plan/component/template_list.dart
  lib/ui/plan/plan_create/plan_create_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_more/plan_more_bottom_sheet_view.dart
  lib/ui/plan/plan_main/plan_view.dart
  lib/ui/plan/plan_template/plan_teamplate_view.dart
  lib/ui/plan/plan_template/plan_template_detail_view.dart
Labels: ✨ Feature

#86 [Feat] 플랜 레이아웃
  lib/data_source/plan/plan_data_source.dart
  lib/data_source/task/request_body/task_request_body.dart
  lib/data_source/task/request_body/task_request_body.g.dart
  lib/data_source/task/task_data_source.dart
  lib/data_source/task/task_data_source.g.dart
  lib/repository/plan/model/plan_detail_model.dart
  lib/repository/plan/plan_repository.dart
  lib/repository/task/task_repository.dart
  lib/routes/app_router.dart
  lib/ui/common/comopnent/planit_bottom_sheet.dart
  lib/ui/common/comopnent/planit_button.dart
  lib/ui/plan/component/condition_tip_table_row.dart
  lib/ui/plan/component/plan_list_card.dart
  lib/ui/plan/component/plan_wrap_grid.dart
  lib/ui/plan/component/task_card.dart
  lib/ui/plan/component/template_detail_card.dart
  lib/ui/plan/component/template_list.dart
  lib/ui/plan/plan_create/plan_create_state.dart
  lib/ui/plan/plan_create/plan_create_view.dart
  lib/ui/plan/plan_create/plan_create_view_model.dart
  lib/ui/plan/plan_detail/bottom_sheet/conditional_tip_bottom_sheet.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_more/plan_more_bottom_sheet_state.dart
  lib/ui/plan/plan_detail/bottom_sheet/plan_more/plan_more_bottom_sheet_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_add/task_add_bottom_sheet_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_edit/task_edit_bottom_sheet_state.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_edit/task_edit_bottom_sheet_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_edit/task_edit_bottom_sheet_view_model.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_more/task_more_bottom_sheet_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_more/task_more_bottom_sheet_view_model.dart
  lib/ui/plan/plan_detail/plan_detail_state.dart
  lib/ui/plan/plan_detail/plan_detail_view.dart
  lib/ui/plan/plan_detail/plan_detail_view_model.dart
  lib/ui/plan/plan_main/plan_all_view.dart
  lib/ui/plan/plan_main/plan_state.dart
  lib/ui/plan/plan_main/plan_view.dart
  lib/ui/plan/plan_template/plan_teamplate_view.dart
  lib/ui/plan/plan_template/plan_template_detail_view.dart
  lib/ui/plan/plan_template/plan_template_detail_view_model.dart
Labels: ✨ Feature

#94 [Feat] 로그인 로딩에 딤 처리
  lib/routes/app_router_interceptor.dart
  lib/ui/common/comopnent/planit_dim_loading.dart
  lib/ui/login/login_view.dart
  lib/ui/login/tos_view.dart
Labels: ✨ Feature

#96 [Fix] 아카이빙 UI 수정
  lib/data_source/task/request_body/routine_request_body.dart
  lib/data_source/task/request_body/routine_request_body.g.dart
  lib/repository/archiving/model/archiving_restart_model.dart
  lib/repository/task/task_repository.dart
  lib/ui/archiving/archiving_complete/archiving_complete_naviagtor.dart
  lib/ui/archiving/archiving_complete/archiving_complete_view.dart
  lib/ui/archiving/archiving_detail/archiving_detail_view.dart
  lib/ui/archiving/archiving_main/archiving_view.dart
  lib/ui/archiving/archiving_main/archiving_view_model.dart
  lib/ui/archiving/archiving_restart/archiving_restart_state.dart
  lib/ui/archiving/archiving_restart/archiving_restart_view.dart
  lib/ui/archiving/archiving_restart/archiving_restart_view_model.dart
  lib/ui/plan/component/task_card.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_edit/task_edit_bottom_sheet_view.dart
  lib/ui/plan/plan_detail/bottom_sheet/task_edit/task_edit_bottom_sheet_view_model.dart
Labels: 🐞 BugFix
